GET http://localhost:8080/ebookAll
Accept: application/json

###

GET http://localhost:8080/ebook/getEbookListByPage?page=1&size=3&category2Id=213
Accept: application/json

###

GET http://localhost:8080/category/allList