GET http://localhost:8080/ebookAll
Accept: application/json

###

GET http://localhost:8080/ebook/getEbookListByPage?page=1&size=3
Accept: application/json

###

GET http://localhost:8080/doc/allList?ebookId=1

###
GET http://localhost:8080/redis/set/123/test
Accept: application/json

###

GET http://localhost:8080/redis/get/2806384514860064
Accept: application/json

###

GET http://localhost:8080/ebook-snapshot/get30Statistic
Accept: application/json

###
